version: "3"

services:
  zookeeper1:
    image: zookeeper:3.8
#    networks:
#      - zk_network
    container_name: zoo1
    hostname: zoo1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      #- ZOO_SERVERS=zoo1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    volumes:
      - "./zoo1/data:/data"
      - "./zoo1/datalog:/datalog"
      - "./zoo1/conf:/conf"
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    
#networks:
#  zk_network:
#    driver: bridge
