version: "3"
services:
  dubbo-admin:
    image: apache/dubbo-admin:0.6.0
#    networks:
#      - zookeeper_zk_network
    container_name: dubbo-admin
    hostname: dubbo-admin
    # volumes:
    #   - "./application.properties:/source/application.properties"
    #   - "./entrypoint.sh:/usr/local/bin/entrypoint.sh"
    ports:
      - '8082:8080'
    environment:
      - admin.registry.address=zookeeper://172.31.103.46:2181
      - admin.config-center=zookeeper://172.31.103.46:2181
      - admin.metadata-report.address=zookeeper://172.31.103.46:2181

#networks:
#  zookeeper_zk_network:
#    external: true
