version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - "808:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./ssh/:/var/jenkins_home/.ssh
  #ssh-agent:
  #  image: jenkins/ssh-agent
volumes:
  jenkins_home:
