version: '3.3'
services:
  redis6379:
    #network_mode: 'host'
    image: redis:6.2.7
    container_name: redis
    # restart: always
    #logging:
    #  driver: 'json-file'
    #  options:
    #    max-size: '5g'
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs:/logs
    command: redis-server /usr/local/etc/redis/redis.conf
